version: "3.9"

services:
  nuxt:
    build:
      context: .
      dockerfile: ./docker/nuxt/Dockerfile
    command: node /usr/src/app/.output/server/index.mjs
    networks:
      - local_network

  nginx:
    image: nginx:1.22.0-alpine
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - local_network
    depends_on:
      - nuxt

networks:
  local_network:
    driver: bridge